#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=gorman-gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --time=3-23:00:00
#SBATCH --job-name dataset_collector


echo "Starting job at $(date)"

# python dataset_collector.py --env 2d --env-id 9 --save-every 250 --num-iter 10000 --num-nodes 3000

python dataset_collector_3d.py --env 3d --env-id 9 --save-every 200 --num-iter 10000 --num-nodes 2500

echo "Done"

