#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=jacobi-all
# SBATCH --mem-per-cpu=256G
#SBATCH --time=14:00:00
#SBATCH --job-name prm



# BATCH --mem-per-cpu=196G

echo "Starting job at $(date)"

python prm_3d.py --env 2d --show-animation --save-every 250 --env-id 9

echo "Done"
