#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=gorman-gpu
# SBATCH --mem-per-cpu=196G
#SBATCH --time=4:00:00
#SBATCH --job-name prm



# BATCH --mem-per-cpu=196G

echo "Starting job at $(date)"

python prm.py

echo "Done"
