#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=jacobi-all
# SBATCH --mem-per-cpu=256G
#SBATCH --time=12:00:00
#SBATCH --job-name prm



# BATCH --mem-per-cpu=196G

echo "Starting job at $(date)"

python prm_3d.py --env-id 0 --env 3d --save-every 100


echo "Done"
