#!/bin/bash
# FILENAME:  rob_train

#SBATCH --nodes=1
#SBATCH --partition=gorman-gpu
#SBATCH --mem-per-cpu=64G
#SBATCH --gpus-per-node=1
#SBATCH --time=23:00:00
#SBATCH --job-name rob_train


python train.py --N 10
