#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=cuda-gpu
# SBATCH --mem-per-cpu=64G
#SBATCH --time=10:00:00
#SBATCH --job-name prm



# BATCH --mem-per-cpu=196G

echo "Starting job at $(date)"

python prm_3d.py --env 3d

echo "Done"
