#!/bin/bash
# FILENAME:  job_prm

#SBATCH --nodes=1
#SBATCH --partition=jacobi-all
#SBATCH --time=12:00:00
#SBATCH --job-name prm


echo "Starting job at $(date)"

python prm_3d.py --env-id 9 --env 3d --save-every 250 


echo "Done"
